apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ai-service
          env:
            - name: FLASK_ENV
              value: "development"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
