apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pfe-dev

resources:
  - ../../base

patches:
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: backend

  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend

images:
  - name: moatazbench/pfe-backend
    newTag: a34cb2bb1ab8ae5a03977e9d278f7231e33c98a1
  - name: moatazbench/pfe-frontend
    newTag: a34cb2bb1ab8ae5a03977e9d278f7231e33c98a1