apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pfe-dev

resources:
  - ../../base

patches:
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: backend

  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend

images:
  - name: moatazbench/pfe-backend
    newTag: 675a3825928477fa505c9e54da32100147058ae3
  - name: moatazbench/pfe-frontend
    newTag: 675a3825928477fa505c9e54da32100147058ae3