apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pfe-dev

resources:
  - ../../base

patches:
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: backend

  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend

images:
  - name: moatazbench/pfe-backend
    newTag: 15611bd6a0ca197a13de062e01bbb9980e5e1b38
  - name: moatazbench/pfe-frontend
    newTag: 15611bd6a0ca197a13de062e01bbb9980e5e1b38